In [20]:
import pandas as pd
import numpy as np

In [28]:
food_balance = pd.read_csv('FoodBalanceSheets_E_Africa_NOFLAG.csv' ,encoding='ISO-8859–1')
food_balance.head(20)

,Area Code,Area,Item Code,Item,Element Code,Element,Unit,Y2014,Y2015,Y2016,Y2017,Y2018
0,4,Algeria,2501,Population,511,Total Population - Both sexes,1000 persons,38924.00,39728.00,40551.00,41389.00,42228.00
1,4,Algeria,2501,Population,5301,Domestic supply quantity,1000 tonnes,0.00,0.00,0.00,0.00,0.00
2,4,Algeria,2901,Grand Total,664,Food supply (kcal/capita/day),kcal/capita/day,3377.00,3379.00,3372.00,3341.00,3322.00
3,4,Algeria,2901,Grand Total,674,Protein supply quantity (g/capita/day),g/capita/day,94.90,94.35,94.72,92.82,91.83
4,4,Algeria,2901,Grand Total,684,Fat supply quantity (g/capita/day),g/capita/day,80.06,79.36,77.40,80.19,77.28
5,4,Algeria,2903,Vegetal Products,664,Food supply (kcal/capita/day),kcal/capita/day,2932.00,2958.00,2941.00,2921.00,2932.00
6,4,Algeria,2903,Vegetal Products,674,Protein supply quantity (g/capita/day),g/capita/day,67.14,67.38,67.37,66.11,67.10
7,4,Algeria,2903,Vegetal Products,684,Fat supply quantity (g/capita/day),g/capita/day,53.84,54.72,52.04,55.59,54.57
8,4,Algeria,2941,Animal Products,664,Food supply (kcal/capita/day),kcal/capita/day,444.00,421.00,431.00,421.00,390.00
9,4,Algeria,2941,Animal Products,674,Protein supply quantity (g/capita/day),g/capita/day,27.76,26.97,27.35,26.71,24.73
10,4,Algeria,2941,Animal Products,684,Fat supply quantity (g/capita/day),g/capita/day,26.22,24.64,25.37,24.60,22.71
11,4,Algeria,2905,Cereals - Excluding Beer,5511,Production,1000 tonnes,3436.00,3761.00,3445.00,3478.00,6065.00
12,4,Algeria,2905,Cereals - Excluding Beer,5611,Import Quantity,1000 tonnes,12604.00,13983.00,13523.00,13039.00,13182.00
13,4,Algeria,2905,Cereals - Excluding Beer,5072,Stock Variation,1000 tonnes,684.00,1663.00,905.00,705.00,2226.00
14,4,Algeria,2905,Cereals - Excluding Beer,5911,Export Quantity,1000 tonnes,3.00,7.00,7.00,10.00,17.00
15,4,Algeria,2905,Cereals - Excluding Beer,5301,Domestic supply quantity,1000 tonnes,15353.00,16075.00,16056.00,15803.00,17004.00
16,4,Algeria,2905,Cereals - Excluding Beer,5521,Feed,1000 tonnes,4725.00,5070.00,4838.00,4667.00,5266.00
17,4,Algeria,2905,Cereals - Excluding Beer,5527,Seed,1000 tonnes,177.00,189.00,197.00,202.00,278.00
18,4,Algeria,2905,Cereals - Excluding Beer,5123,Losses,1000 tonnes,1084.00,1203.00,1148.00,1121.00,1253.00
19,4,Algeria,2905,Cereals - Excluding Beer,5131,Processing,1000 tonnes,35.00,38.00,37.00,33.00,44.00

In [22]:
food_balance.shape

(60943, 12)

In [50]:
food_balance.groupby('Element').sum().head(50)

,Area Code,Item Code,Element Code,Y2014,Y2015,Y2016,Y2017,Y2018
Element,,,,,,,,
Domestic supply quantity,708993,14197445,28068795,1996716.35,2021493.55,2044842.70,2088198.10,2161192.10
Export Quantity,599910,11840553,26026133,150020.64,157614.47,151920.46,182338.80,181594.80
Fat supply quantity (g/capita/day),675050,13535000,3435732,10225.56,10235.74,10102.77,10253.84,10258.69
Feed,176272,3538507,7282199,216927.89,225050.22,228958.65,223705.68,233489.68
Food,663295,13285035,25406622,1212332.49,1232361.10,1247022.17,1258888.28,1303841.28
Food supply (kcal/capita/day),674057,13511060,3329296,454257.00,453383.00,451810.00,454681.00,455261.00
Food supply quantity (kg/capita/yr),658446,13185401,3163725,49650.63,49345.13,48985.28,48690.04,49056.85
Import Quantity,688174,13795966,28834929,274144.48,267018.46,286582.78,294559.09,287997.09
Losses,274353,5424803,10292107,153223.00,155439.00,157787.00,160614.00,163902.00
Other uses (non-food),235554,4729749,8926728,78718.13,66254.41,69563.68,91645.97,91300.97
Processing,271940,5350416,10313310,282923.00,287929.00,280631.00,292836.00,308429.00
Production,526751,10450053,21388191,1931287.75,1947019.39,1943537.15,2030056.89,2075072.89
Protein supply quantity (g/capita/day),675050,13535000,3385502,11836.46,11833.95,11779.69,11842.45,11833.56
Residuals,623271,12421089,24066350,30149.00,30045.00,37224.00,35500.00,34864.00
Seed,103537,2035933,4211574,21922.92,23976.82,23389.20,24870.14,25263.14
Stock Variation,571566,11329527,21464704,58749.83,34910.99,33140.12,54316.91,20577.91
Total Population - Both sexes,6020,112545,22995,1031585.00,1058081.00,1085107.00,1112641.00,1140605.00
Tourist consumption,50308,1486528,2869905,416.00,349.00,89.00,91.00,90.00

In [25]:
food_balance.mean()

C:\Users\Peculiar Abolade\AppData\Local\Temp\ipykernel_15308\4138855164.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  food_balance.mean()

Area Code        134.265576
Item Code       2687.176706
Element Code    3814.856456
Y2014            134.196282
Y2015            135.235966
Y2016            136.555222
Y2017            140.917765
Y2018            143.758381
dtype: float64

In [24]:
food_balance.std()

C:\Users\Peculiar Abolade\AppData\Local\Temp\ipykernel_15308\1014769833.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  food_balance.std()

Area Code         72.605709
Item Code        146.055739
Element Code    2212.007033
Y2014           1567.663696
Y2015           1603.403984
Y2016           1640.007194
Y2017           1671.862359
Y2018           1710.782658
dtype: float64

In [13]:
food_balance.isnull().sum()

Area Code          0
Area               0
Item Code          0
Item               0
Element Code       0
Element            0
Unit               0
Y2014           1589
Y2015           1548
Y2016           1535
Y2017           1506
Y2018           1436
dtype: int64

In [27]:
food_balance.nunique()

Area Code         49
Area              49
Item Code        122
Item             119
Element Code      18
Element           18
Unit               5
Y2014           4493
Y2015           4520
Y2016           4520
Y2017           4537
Y2018           4591
dtype: int64

In [51]:
food_balance.groupby('Item').sum().head(50)

,Area Code,Item Code,Element Code,Y2014,Y2015,Y2016,Y2017,Y2018
Item,,,,,,,,
"Alcohol, Non-Food",38447,752497,1515090,2403.00,2180.00,2223.00,2348.00,2293.00
Alcoholic Beverages,75016,1649136,2171381,102410.11,98783.72,96958.75,95581.06,97847.27
Animal Products,18060,397035,90990,11935.65,11811.73,11661.69,11547.65,11578.61
Animal fats,85279,1882494,2567303,209460.54,200675.72,183314.22,269617.53,269648.27
Apples and products,69280,1352989,1920418,9499.23,10559.15,9853.26,10198.90,9640.51
"Aquatic Animals, Others",47420,966381,1139179,14.55,9.26,6.17,5.92,5.92
Aquatic Plants,51178,1057275,1278386,507.29,631.23,470.21,452.02,452.02
"Aquatic Products, Other",52570,1160712,1320249,519.62,638.42,475.08,456.65,456.65
Bananas,68496,1338880,1894890,53267.31,55046.76,54376.07,53008.82,55549.23
Barley and products,76321,1432410,2243002,25384.66,29153.44,24706.08,26176.98,31253.70
Beans,78001,1476680,2263509,19207.68,20315.77,19037.50,21351.42,20121.14
Beer,65975,1314720,1813728,41879.92,42053.67,42540.48,41962.92,41612.12
"Beverages, Alcoholic",65918,1313052,1807946,3067.16,2818.38,2834.92,3115.24,2979.21
"Beverages, Fermented",65203,1299273,1774758,50536.78,47447.92,45478.53,43958.75,46874.94
Bovine Meat,70033,1431044,1963251,22098.60,22766.42,22411.18,22612.86,23926.30
"Butter, Ghee",60516,1238480,1594919,1249.29,1165.69,1199.87,1116.68,1175.59
Cassava and products,73208,1385004,2081916,405442.57,410235.89,415730.20,401440.17,435862.14
Cephalopods,58593,1233636,1571763,423.03,496.95,503.64,532.14,532.07
Cereals - Excluding Beer,95370,2074170,2976719,851924.06,845669.36,875974.56,905221.25,903280.79
"Cereals, Other",79505,1489320,2326237,18689.11,18912.55,19877.56,20615.95,22125.96
"Citrus, Other",70239,1367122,1954812,14533.46,15188.91,15515.30,15650.97,15804.14
Cloves,53398,1064726,1420590,77.37,77.29,78.27,82.32,82.36
Cocoa Beans and products,70862,1398123,1998287,7166.65,7671.59,7510.86,8638.32,8353.83
Coconut Oil,69418,1330248,1959863,517.56,556.18,549.43,516.99,537.70
Coconuts - Incl Copra,74263,1410560,2104761,6568.33,6646.28,6577.23,6478.91,6526.12
Coffee and products,72724,1433350,2070618,3677.92,3849.99,4115.34,3861.45,4009.65
Cottonseed,44285,841911,1768564,8108.00,7998.00,8093.00,8623.00,8802.00
Cottonseed Oil,67319,1287500,1881106,1379.76,1507.90,1366.75,1403.25,1421.56
Cream,55778,1141088,1421946,237.52,233.37,267.84,228.95,271.61
Crustaceans,64831,1338260,1761859,734.07,732.86,717.30,834.82,833.61
Dates,64881,1278072,1771007,10183.80,11108.74,10904.81,11088.61,11454.52
Demersal Fish,62436,1292616,1677632,5845.93,6123.88,5691.28,6618.70,6616.23
Eggs,154150,3250703,4426246,20563.36,21431.48,20428.82,21749.74,20638.48
"Fats, Animals, Raw",79842,1636726,2341974,1596.09,1729.80,1614.01,1783.67,1707.11
"Fish, Body Oil",56619,1154115,1462871,170.51,193.73,167.09,219.65,219.65
"Fish, Liver Oil",48755,979264,1197204,38.13,6.36,15.87,48.02,48.02
"Fish, Seafood",71756,1583600,2039247,43240.02,43293.41,43727.14,44849.35,44810.20
Freshwater Fish,64920,1333563,1761607,13161.92,13195.86,13908.83,14258.00,14244.98
Fruits - Excluding Wine,79433,1725129,2313131,273559.54,282857.19,277458.49,284309.07,290381.46
"Fruits, Other",76833,1506750,2224160,53970.46,57504.33,57730.21,59463.60,61370.30
Grand Total,18060,391635,90990,119183.84,118937.92,118434.34,119264.82,119388.06
Grapefruit and products,69139,1340469,1896997,2359.01,2352.21,2129.03,2137.02,2449.18
Grapes and products (excl wine),70255,1367640,1946827,13820.84,14607.88,14235.15,14591.98,13992.75
Groundnut Oil,70147,1355444,1971148,5479.80,5561.17,5511.52,5389.20,5463.60
Groundnuts (Shelled Eq),82299,1577052,2457038,42384.73,42199.35,43962.23,44684.53,46513.58
Honey,69241,1413675,1908893,679.11,713.12,664.78,660.07,681.56
Infant food,59745,1197960,1547996,328.49,340.38,331.92,311.92,298.01
"Lemons, Limes and products",70391,1358240,1938946,3429.42,3667.51,3600.68,4191.49,4220.50
Maize Germ Oil,64256,1234196,1747258,874.59,950.64,1000.13,1075.37,865.77
Maize and products,91790,1727118,2832303,291731.71,287659.14,294568.76,323471.75,297383.10